# Generated by Django 5.1.1 on 2024-09-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("employee_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Укажите имя сотрудника",
                        max_length=100,
                        null=True,
                        verbose_name="Имя сотрудника",
                    ),
                ),
                (
                    "surname",
                    models.CharField(
                        help_text="Укажите фамилию сотрудника",
                        max_length=100,
                        verbose_name="Фамилия сотрудника",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                ("employee_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "position",
                    models.CharField(
                        help_text="Укажите должность сотрудника",
                        max_length=150,
                        verbose_name="Должность сотрудника",
                    ),
                ),
            ],
            options={
                "verbose_name": "Должность",
                "verbose_name_plural": "Должности",
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        help_text="Укажите название департамента",
                        max_length=150,
                        verbose_name="Название департамента",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        help_text="Укажите должность сотрудника",
                        max_length=150,
                        verbose_name="Должность сотрудника",
                    ),
                ),
                (
                    "surname",
                    models.CharField(
                        help_text="Укажите фамилию сотрудника",
                        max_length=150,
                        verbose_name="Фамилия сотрудника",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отдел",
                "verbose_name_plural": "Отделы",
                "unique_together": {("position", "surname")},
            },
        ),
    ]
